require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'

platform :ios, '10.0'

target 'TestBoilerplate' do
  config = use_native_modules!
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
  # for Analytics without IDFA collection capability

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  use_react_native!(:path => config["reactNativePath"])
  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'
  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'
  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    'FaceDetectorMLKit'
  ]
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-in-app-review', :path => '../node_modules/react-native-in-app-review'

  target 'TestBoilerplateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'TestBoilerplate-tvOS' do
  # Pods for TestBoilerplate-tvOS

  target 'TestBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
